### ISSUE TITLE
Can we get the code to visualize the keypoints on a image or video?

### ISSUE THREAD

**Issue by S20-Raj** [VlSomers/keypoint_promptable_reidentification#2]

**Comment by VlSomers** [comment]
Hi @S20-Raj, the code for inference on an image is in [demo.py](https://github.com/VlSomers/keypoint_promptable_reidentification/blob/main/demo.py). The code for inference on a video to perform pose tracking will not be released shortly, since I'm busy with other tasks. Please come back later this year as I plan to release it at some point ;)

**Comment by VlSomers** [comment]
Can you share the full stacktrace?

**Comment by YXHJSJ** [comment]
Here is the full stacktrace:


Traceback (most recent call last):  File "/mnt/8T/wzw/keypoint_promptable_reidentification/demo.py", line 8, in <module>
    from torchreid.metrics.distance import compute_distance_matrix_using_bp_features
  File "/mnt/8T/wzw/keypoint_promptable_reidentification/torchreid/__init__.py", line 3, in <module>
    from torchreid import data, optim, utils, engine, losses, models, metrics
  File "/mnt/8T/wzw/keypoint_promptable_reidentification/torchreid/data/__init__.py", line 3, in <module>
    from .datasets import (
  File "/mnt/8T/wzw/keypoint_promptable_reidentification/torchreid/data/datasets/__init__.py", line 5, in <module>
    from .image import (
  File "/mnt/8T/wzw/keypoint_promptable_reidentification/torchreid/data/datasets/image/__init__.py", line 3, in <module>
    from .grid import GRID
  File "/mnt/8T/wzw/keypoint_promptable_reidentification/torchreid/data/datasets/image/grid.py", line 6, in <module>
    from torchreid.utils import read_json, write_json
  File "/mnt/8T/wzw/keypoint_promptable_reidentification/torchreid/utils/__init__.py", line 12, in <module>
    from .model_complexity import compute_model_complexity
  File "/mnt/8T/wzw/keypoint_promptable_reidentification/torchreid/utils/model_complexity.py", line 10, in <module>
    from torchreid.models import SamReID
  File "/mnt/8T/wzw/keypoint_promptable_reidentification/torchreid/models/__init__.py", line 3, in <module>
    from .kpr import KPR
  File "/mnt/8T/wzw/keypoint_promptable_reidentification/torchreid/models/kpr.py", line 7, in <module>
    from torchvision.ops import FeaturePyramidNetwork
  File "/mnt/8T/wzw/anaconda3/envs/kpr/lib/python3.10/site-packages/torchvision/__init__.py", line 5, in <module>
    from torchvision import datasets, io, models, ops, transforms, utils
  File "/mnt/8T/wzw/anaconda3/envs/kpr/lib/python3.10/site-packages/torchvision/models/__init__.py", line 17, in <module>
    from . import detection, optical_flow, quantization, segmentation, video
  File "/mnt/8T/wzw/anaconda3/envs/kpr/lib/python3.10/site-packages/torchvision/models/detection/__init__.py", line 1, in <module>
    from .faster_rcnn import *
  File "/mnt/8T/wzw/anaconda3/envs/kpr/lib/python3.10/site-packages/torchvision/models/detection/faster_rcnn.py", line 16, in <module>
    from .anchor_utils import AnchorGenerator
  File "/mnt/8T/wzw/anaconda3/envs/kpr/lib/python3.10/site-packages/torchvision/models/detection/anchor_utils.py", line 10, in <module>
    class AnchorGenerator(nn.Module):
  File "/mnt/8T/wzw/anaconda3/envs/kpr/lib/python3.10/site-packages/torchvision/models/detection/anchor_utils.py", line 63, in AnchorGenerator
    device: torch.device = torch.device("cpu"),
/mnt/8T/wzw/anaconda3/envs/kpr/lib/python3.10/site-packages/torchvision/models/detection/anchor_utils.py:63: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at /opt/conda/conda-bld/pytorch_1666642969563/work/torch/csrc/utils/tensor_numpy.cpp:77.)
  device: torch.device = torch.device("cpu"),
Overwriting current config with config loaded from pretrained_models/kpr_occ_pt_IN_82.34_92.33_42323828.pth.tar
Save dir created at /mnt/8T/wzw/keypoint_promptable_reidentification/logs/607167128
Traceback (most recent call last):
  File "/mnt/8T/wzw/anaconda3/envs/kpr/lib/python3.10/site-packages/urllib3/connection.py", line 199, in _new_conn
    sock = connection.create_connection(
  File "/mnt/8T/wzw/anaconda3/envs/kpr/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/mnt/8T/wzw/anaconda3/envs/kpr/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/8T/wzw/anaconda3/envs/kpr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "/mnt/8T/wzw/anaconda3/envs/kpr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 490, in _make_request
    raise new_e
  File "/mnt/8T/wzw/anaconda3/envs/kpr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/mnt/8T/wzw/anaconda3/envs/kpr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/mnt/8T/wzw/anaconda3/envs/kpr/lib/python3.10/site-packages/urllib3/connection.py", line 693, in connect
    self.sock = sock = self._new_conn()
  File "/mnt/8T/wzw/anaconda3/envs/kpr/lib/python3.10/site-packages/urllib3/connection.py", line 214, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f5e7dc712d0>: Failed to establish a new connection: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/8T/wzw/anaconda3/envs/kpr/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/mnt/8T/wzw/anaconda3/envs/kpr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "/mnt/8T/wzw/anaconda3/envs/kpr/lib/python3.10/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /timm/swinv2_base_window12to16_192to256.ms_in22k_ft_in1k/resolve/main/pytorch_model.bin (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5e7dc712d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/8T/wzw/anaconda3/envs/kpr/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1746, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(
  File "/mnt/8T/wzw/anaconda3/envs/kpr/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/mnt/8T/wzw/anaconda3/envs/kpr/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1666, in get_hf_file_metadata
    r = _request_wrapper(
  File "/mnt/8T/wzw/anaconda3/envs/kpr/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 364, in _request_wrapper
    response = _request_wrapper(
  File "/mnt/8T/wzw/anaconda3/envs/kpr/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 387, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
  File "/mnt/8T/wzw/anaconda3/envs/kpr/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/mnt/8T/wzw/anaconda3/envs/kpr/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/mnt/8T/wzw/anaconda3/envs/kpr/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 93, in send
    return super().send(request, *args, **kwargs)
  File "/mnt/8T/wzw/anaconda3/envs/kpr/lib/python3.10/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /timm/swinv2_base_window12to16_192to256.ms_in22k_ft_in1k/resolve/main/pytorch_model.bin (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5e7dc712d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"), '(Request ID: 78575f1f-3d5c-494d-8837-53a95a7d1588)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/8T/wzw/keypoint_promptable_reidentification/demo.py", line 45, in <module>
    extractor = KPRFeatureExtractor(kpr_cfg)
  File "/mnt/8T/wzw/keypoint_promptable_reidentification/torchreid/tools/feature_extractor.py", line 72, in __init__
    model = build_model(cfg)
  File "/mnt/8T/wzw/keypoint_promptable_reidentification/torchreid/scripts/builder.py", line 252, in build_model
    model = torchreid.models.build_model(
  File "/mnt/8T/wzw/keypoint_promptable_reidentification/torchreid/models/__init__.py", line 145, in build_model
    return __model_factory[name](
  File "/mnt/8T/wzw/keypoint_promptable_reidentification/torchreid/models/kpr.py", line 49, in __init__
    self.backbone_appearance_feature_extractor = models.build_model(self.model_cfg.backbone,
  File "/mnt/8T/wzw/keypoint_promptable_reidentification/torchreid/models/__init__.py", line 145, in build_model
    return __model_factory[name](
  File "/mnt/8T/wzw/keypoint_promptable_reidentification/torchreid/models/promptable_timm_swin.py", line 90, in timm_swin
    model = SwinTransformer(
  File "/mnt/8T/wzw/keypoint_promptable_reidentification/torchreid/models/promptable_timm_swin.py", line 14, in __init__
    model = timm.create_model(name,
  File "/mnt/8T/wzw/anaconda3/envs/kpr/lib/python3.10/site-packages/timm/models/_factory.py", line 117, in create_model
    model = create_fn(
  File "/mnt/8T/wzw/anaconda3/envs/kpr/lib/python3.10/site-packages/timm/models/swin_transformer_v2.py", line 1035, in swinv2_base_window12to16_192to256
    return _create_swin_transformer_v2(
  File "/mnt/8T/wzw/anaconda3/envs/kpr/lib/python3.10/site-packages/timm/models/swin_transformer_v2.py", line 888, in _create_swin_transformer_v2
    model = build_model_with_cfg(
  File "/mnt/8T/wzw/anaconda3/envs/kpr/lib/python3.10/site-packages/timm/models/_builder.py", line 427, in build_model_with_cfg
    load_pretrained(
  File "/mnt/8T/wzw/anaconda3/envs/kpr/lib/python3.10/site-packages/timm/models/_builder.py", line 205, in load_pretrained
    state_dict = load_state_dict_from_hf(pretrained_loc, weights_only=True)
  File "/mnt/8T/wzw/anaconda3/envs/kpr/lib/python3.10/site-packages/timm/models/_hub.py", line 192, in load_state_dict_from_hf
    cached_file = hf_hub_download(hf_model_id, filename=filename, revision=hf_revision)
  File "/mnt/8T/wzw/anaconda3/envs/kpr/lib/python3.10/site-packages/huggingface_hub/utils/_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "/mnt/8T/wzw/anaconda3/envs/kpr/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/mnt/8T/wzw/anaconda3/envs/kpr/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1232, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "/mnt/8T/wzw/anaconda3/envs/kpr/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1339, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "/mnt/8T/wzw/anaconda3/envs/kpr/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1857, in _raise_on_head_call_error
    raise LocalEntryNotFoundError(
huggingface_hub.errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

**Comment by VlSomers** [comment]
It seems to be an issue related to your internet connection or accessibility to the Hugging Face hub, have you tried to search for this error online?

**Comment by YXHJSJ** [comment]
Thank you so much! I successfully resolved the issue by adding the following command in the terminal: 
export HF_ENDPOINT="https://hf-mirror.com".

**Comment by mgreyes427** [comment]
> se come back later this year as I plan to release it at

Are you planning t continue with this? Really interested on see how it work on videos
